version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: mineadmin-frontend-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
    networks:
      - mineadmin-frontend-network

networks:
  mineadmin-frontend-network:
    driver: bridge
